config/routes.rb
PortfolioViny::Application.routes.draw do
  namespace :admin do
    match 'login' => 'user_session#new', :as => :login
    match 'logout' => 'user_session#destroy', :as => :logout
    resource :user_session, :only => [:show, :new, :create, :destroy],
             :controller => :user_session
    resource :user, :only => [:edit, :update],
             :controller => :user
    resources :static_contents, :only => [:index, :show, :edit, :update]
    resources :external_links
    resources :achievements
    resources :resumes
  end

  root :to => 'home#index'
  match 'portfolio/:section' => 'portfolio#index', :as => :portfolio_section
  match 'portfolio/:section/:subsection/:title' => 'portfolio#show',
    :as => :portfolio_achievement
  match 'links' => 'external_links#index', :as => :external_links
  match 'bio' => 'bio#index', :as => :bio
  match 'sitemap' => 'sitemap#show', :as => :sitemap
  resources :contacts, :only => [:index, :create]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.haml
- specific_includes do
  = stylesheet_link_tag 'home'
#virginie_blancher
  %span Virginie Blancher
%div#links
  - [ 'couleur_bd',
      'illustration',
      'graphisme',
      'chiyogami',
      'croquis' ].each do |section|
    = link_to(portfolio_path(section), :id => "to_#{section}") do
      %span= t(".links.#{section}")
  = link_to(contacts_path, :id => 'to_contact') do
    %span= t(".links.contact")
  = link_to('https://plus.google.com/u/0/photos/109435610364015484658/albums', :id => 'to_inspirations') do
    %span= t('.links.inspirations')
  = link_to(bio_path, :id => "to_bio_et_cv") do
    %span= t(".links.bio_et_cv")
  = link_to(external_links_path, :id => "to_liens") do
    %span= t(".links.liens")